var mensagem = "Seja bem-vindo!";
var temporadaFriends = 10;
var estudoAngular = true;
var listaDeFrutas = ['Uva', 'Banana', 'Abacaxi'];
var listaDeFrutas2 = ['Uva', 'Banana', 'Abacaxi']; //não pode repetir o nome
var notasDasProvas = [7.5, 8, 9];
var notasDasProvas2 = [7.5, 8, 9];
//estudoAngular = 'Teste'; //não pode
//mensagem = 10; não pode
